### ISSUE TITLE
pep517:some circular dependencies

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#2210]
lin python-pep517
Checking dependencies for python-pep517 
Checking dependencies for python-py 
Checking dependencies for python-setuptools-scm 
Checking dependencies for python-apipkg 
Checking dependencies for python-hatchling 
Checking dependencies for python-hatch-vcs 
Checking dependencies for python-iniconfig 
Building python-setuptools-scm version 7.0.5
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 39, in <module>
    import pep517.wrappers
ModuleNotFoundError: No module named 'pep517'

**Comment by stumbles** [comment]
It compiles fine here, unless your pasting from CI and if so I have no control over CI.
